function [ eta_star ] = Eta_star_gen( eta_1, eta_2, eta_3, beta)
%Eta_star_gen: This function takes in eta_1, eta_2 and eta_3 generated by
%Eta_gen or Eta_gen_comb and a quantile index beta, and outputs eta_star as
%given in equation 20 of Guggenberger

% Error if beta is not between 0 and 1
if beta < 0 || beta > 1
    error('The quantile beta must be between 0 and 1');
end

% Compute the 1 - beta quantile of a chi square distribution with 1 degree
% of freedom
quant_xisq = chi2inv(1 - beta, 1);

% Compute the indicator functions
eta3_leq = (eta_3 <= quant_xisq);
eta3_more = ~eta3_leq;

% Compute eta_h_star
eta_star = eta_2 .* eta3_leq + eta_1 .* eta3_more;

end

